### PR TITLE
Support fastai_optimizer for all lr schedulers

### PR DESCRIPTION
**Pull request by s-ryosky**
ref: #21

### CODE REVIEW

**Comment by poodarchu** [comment]
Is it correct to use optimizer_config.type rather than optimizer_config.TYPE? It's mismatch with config file.

**Comment by s-ryosky** [comment]
I have used ".type" rather than ".TYPE" because you have set "type" in config files.
It depends the way to specify the attributes.

https://github.com/poodarchu/Det3D/blob/7b28766a8fb61f223ecaae012c2447d8ad2138f3/examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py#L344-L348

**Comment by poodarchu** [comment]
please keep it as Upper Case to indicate that thoese options are corresponding to config files.

**Comment by s-ryosky** [comment]
Do you mean to change option names in config files to uppercase?

If so, then may I change all of them to uppercase?
Or may I change only option names which are related to optimizer config to uppercase?

Now all option names in config files are written as lowercase and 
In your implementation the most of options are used as follows: 
https://github.com/poodarchu/Det3D/blob/56402d4761a5b73acd23080f537599b0888cce07/det3d/torchie/apis/train.py#L229-L230

**Comment by poodarchu** [comment]
YES, UPPER CASE is more suitable here

**Comment by s-ryosky** [comment]
Fix.

It keeps option names of fastai_optimizer as uppercase.
The others are lowercase.

**Comment by poodarchu** [comment]
please fix commit history, unrelated files are included in this merge.

**Comment by s-ryosky** [comment]
sorry, fix it.

**Comment by s-ryosky** [comment]
any feedback?

**Pull request merged**
