### PR TITLE
improve baselines  Closes #55, Closes #47, Closes #80, Closes #117 

### LINKED ISSUE #47: Unable to reproduce CBGS's results on NuScenes
Comparing to the current master branch, I made two changes in order to fix the NaN training loss. 

The first change is described in #46 . 

The second change is to add what's below before [line 193 in losses.py](https://github.com/poodarchu/Det3D/blob/master/det3d/models/losses/losses.py#L193)
```
# FIX NaN TARGETS 
target_tensor = torch.where(
    torch.isnan(target_tensor), prediction_tensor, target_tensor
)
```

Besides, I set 
```
norm_cfg = dict(type='SyncBN', eps=1e-3, momentum=0.01)
```
in `examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py` and 
```
torch.backends.cudnn.benchmark = True
```
in `tools/train.py`. 

Here are my results on the validation set after training 20 epochs: 
```
car Nusc dist AP@0.5, 1.0, 2.0, 4.0
59.25, 71.87, 77.22, 79.63 mean AP: 0.7199402759604012
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0
17.96, 35.01, 43.00, 47.15 mean AP: 0.357782470829584
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0
0.00, 1.28, 6.75, 13.37 mean AP: 0.05348830261303094
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0
23.87, 48.49, 62.98, 66.32 mean AP: 0.5041451034213309
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0
1.94, 14.27, 30.88, 42.11 mean AP: 0.22300031478924093
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0
28.06, 48.97, 57.80, 60.27 mean AP: 0.4877375663669212
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
24.97, 29.29, 30.38, 30.99 mean AP: 0.28906646690838084
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
6.20, 7.36, 7.98, 8.53 mean AP: 0.07516058303100348
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0
62.82, 64.73, 66.83, 69.03 mean AP: 0.658543997130018
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0
42.10, 44.31, 46.23, 50.65 mean AP: 0.4582346501948114
```

Overall the mean AP is **38.2**, which is much lower than what's reported. 

Can someone point me to what I might have missed? Thanks!

### LINKED ISSUE #55: About reproduce CBGS result
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
using the Ego velocity in every annotations, the other config are same.
```
# convert velo from global to lidar
for i in range(len(ref_boxes)):
    velo = np.array([*velocity[i], 0.0])
    velo = velo @ np.linalg.inv(e2g_r_mat).T @ np.linalg.inv(
          l2e_r_mat).T
    velocity[i] = velo[:2]
    velocity = velocity.reshape(-1,2)
```
2. what exact command you run:
```
python3 -m torch.distributed.launch --nproc_per_node=8 ./tools/train.py examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py --work_dir=/home/ubuntu/Documents/Det3D/trained_model
```
3. what you observed:
```
mAP: 0.3719
mATE: 0.3724
mASE: 0.2661
mAOE: 0.9296
mAVE: 1.3655
mAAE: 0.2684
NDS: 0.4023
Eval time: 140.1s

Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.721	0.219	0.158	0.841	1.116	0.230
truck	0.371	0.426	0.198	0.640	1.155	0.307
bus	0.500	0.439	0.174	1.223	2.171	0.431
trailer	0.213	0.687	0.219	0.670	1.371	0.184
construction_vehicle	0.058	0.798	0.481	1.370	0.157	0.372
pedestrian	0.653	0.165	0.287	1.350	0.869	0.439
motorcycle	0.242	0.223	0.243	1.107	3.192	0.153
bicycle	0.043	0.199	0.264	1.111	0.894	0.031
traffic_cone	0.449	0.170	0.348	nan	nan	nan
barrier	0.470	0.398	0.289	0.056	nan	nan
Evaluation nusc: Nusc v1.0-trainval Evaluation
car Nusc dist AP@0.5, 1.0, 2.0, 4.0
59.48, 71.97, 77.40, 79.65 mean AP: 0.7212472062431424
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0
18.48, 36.29, 44.83, 48.91 mean AP: 0.3712787143771077
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0
0.00, 2.09, 8.06, 12.96 mean AP: 0.05777510817362395
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0
23.60, 47.30, 62.94, 66.32 mean AP: 0.5003920838518946
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0
1.66, 13.24, 29.62, 40.49 mean AP: 0.21251682647224052
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0
26.14, 46.78, 55.95, 59.13 mean AP: 0.4700045657239055
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
20.39, 24.74, 25.62, 26.05 mean AP: 0.24202605811125658
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
3.93, 4.27, 4.35, 4.58 mean AP: 0.04280152387228541
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0
62.12, 64.40, 66.13, 68.36 mean AP: 0.6525328516852104
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0
40.81, 43.40, 45.49, 49.80 mean AP: 0.44874109465427564
```
9c9f22a58fdc45f2b8a119cda3554f1f
93fdce35d7db4764ad5f822f57ab49e2

Unable to reproduce the results in model zoo.

## Expected behavior:
the score NDS don't reach the number in released paper, and the AVE number is abnormal large than others, this reproduced result even worse than pointpillars. Is the loss compute func exist some problems leading to this result?

### LINKED ISSUE #80: which config file match the Trained Model named model_epoch_025_step_100100.pth
there are two config file in the dir Det3D/examples/cbgs/configs  lyft*.py and nusc*.py
when I load the model with the file nusc ,the the model unable get right result and as fllow

The model and loaded state dict do not match exactly

unexpected key in source state_dict: model, optimizer, iteration, epoch

missing keys in source state_dict: backbone.middle_conv.8.bn1.running_var, backbone.middle_conv.3.bn2.running_mean, neck.blocks.0.17.bias, backbone.middle_conv.19.bn2.running_mean, backbone.middle_conv.1.running_mean, bbox_head.tasks.2.conv_dir.weight, backbone.middle_conv.4.conv2.bias, backbone.middle_conv.4.conv1.bias, backbone.middle_conv.11.running_mean, backbone.middle_conv.13.conv1.bias, backbone.middle_conv.4.conv2.weight, backbone.middle_conv.1.weight, neck.blocks.0.13.weight, bbox_head.tasks.2.conv_dir.bias, backbone.middle_conv.14.bn1.weight, backbone.middle_conv.5.weight, backbone.middle_conv.6.running_var, backbone.middle_conv.8.conv2.bias, neck.blocks.0.5.weight, backbone.middle_conv.14.bn2.running_mean, backbone.middle_conv.1.bias, backbone.middle_conv.9.bn1.bias, backbone.middle_conv.14.bn2.running_var, backbone.middle_conv.18.bn2.weight, backbone.middle_conv.8.bn1.bias, bbox_head.tasks.3.conv_cls.bias, backbone.middle_conv.16.running_var, backbone.middle_conv.18.bn1.weight, backbone.middle_conv.18.conv1.bias, neck.blocks.1.17.bias, backbone.middle_conv.6.weight, bbox_head.tasks.3.conv_dir.weight, backbone.middle_conv.11.weight, backbone.middle_conv.8.conv1.weight, neck.blocks.0.2.running_mean, backbone.middle_conv.9.conv1.weight, bbox_head.tasks.4.conv_cls.weight, neck.deblocks.0.1.weight, neck.blocks.1.2.running_var, neck.blocks.0.8.bias, backbone.middle_conv.13.bn1.bias, backbone.middle_conv.4.bn2.weight, neck.deblocks.0.1.running_var, backbone.middle_conv.19.bn2.weight, bbox_head.tasks.3.conv_dir.bias, backbone.middle_conv.14.bn2.weight, neck.blocks.1.14.weight, neck.blocks.1.11.weight, backbone.middle_conv.9.conv2.weight, backbone.middle_conv.18.bn2.running_mean, neck.blocks.0.5.running_mean, backbone.middle_conv.3.bn1.bias, neck.deblocks.0.1.running_mean, bbox_head.tasks.1.conv_dir.weight, bbox_head.tasks.5.conv_box.bias, bbox_head.tasks.0.conv_box.weight, backbone.middle_conv.3.bn1.running_mean, neck.blocks.1.8.weight, backbone.middle_conv.4.bn2.bias, neck.blocks.1.8.running_var, neck.blocks.1.2.bias, bbox_head.tasks.0.conv_box.bias, backbone.middle_conv.4.bn1.running_mean, backbone.middle_conv.10.weight, neck.blocks.1.17.running_var, neck.deblocks.1.1.bias, backbone.middle_conv.3.bn1.weight, backbone.middle_conv.9.bn2.weight, bbox_head.tasks.5.conv_dir.bias, backbone.middle_conv.8.bn1.weight, neck.deblocks.1.0.weight, backbone.middle_conv.4.bn2.running_mean, neck.blocks.1.5.bias, backbone.middle_conv.13.bn1.running_var, bbox_head.tasks.4.conv_box.weight, backbone.middle_conv.8.bn2.running_var, neck.blocks.1.2.weight, backbone.middle_conv.11.bias, neck.blocks.1.5.running_var, backbone.middle_conv.19.conv1.bias, backbone.middle_conv.1.running_var, bbox_head.tasks.2.conv_cls.weight, neck.blocks.0.2.weight, backbone.middle_conv.9.bn2.bias, backbone.middle_conv.9.bn1.running_mean, backbone.middle_conv.21.weight, neck.blocks.1.17.running_mean, backbone.middle_conv.8.bn1.running_mean, backbone.middle_conv.13.bn1.weight, bbox_head.tasks.2.conv_cls.bias, backbone.middle_conv.14.bn1.bias, neck.blocks.0.2.bias, neck.blocks.1.16.weight, bbox_head.tasks.5.conv_dir.weight, neck.blocks.1.10.weight, bbox_head.tasks.0.conv_cls.weight, neck.blocks.1.5.weight, bbox_head.tasks.3.conv_box.bias, backbone.middle_conv.14.conv1.weight, backbone.middle_conv.19.bn1.weight, neck.blocks.0.17.running_mean, bbox_head.tasks.4.conv_box.bias, neck.blocks.0.11.bias, neck.blocks.0.17.weight, backbone.middle_conv.3.bn2.running_var, bbox_head.tasks.3.conv_cls.weight, backbone.middle_conv.0.weight, backbone.middle_conv.18.conv1.weight, backbone.middle_conv.18.bn2.running_var, backbone.middle_conv.9.conv1.bias, neck.deblocks.1.1.weight, bbox_head.tasks.1.conv_cls.bias, bbox_head.tasks.3.conv_box.weight, backbone.middle_conv.4.bn2.running_var, neck.blocks.0.5.running_var, backbone.middle_conv.9.conv2.bias, backbone.middle_conv.4.bn1.weight, neck.blocks.0.5.bias, neck.blocks.1.1.weight, backbone.middle_conv.21.bias, backbone.middle_conv.14.conv1.bias, backbone.middle_conv.8.conv1.bias, backbone.middle_conv.6.running_mean, backbone.middle_conv.13.conv1.weight, backbone.middle_conv.9.bn2.running_var, neck.blocks.1.5.running_mean, neck.blocks.0.11.weight, bbox_head.tasks.4.conv_dir.weight, neck.blocks.1.14.running_var, neck.deblocks.0.1.bias, bbox_head.tasks.2.conv_box.bias, backbone.middle_conv.4.conv1.weight, backbone.middle_conv.19.bn2.bias, neck.blocks.0.11.running_mean, neck.blocks.0.11.running_var, backbone.middle_conv.8.bn2.bias, backbone.middle_conv.19.bn2.running_var, backbone.middle_conv.13.bn2.bias, backbone.middle_conv.8.conv2.weight, neck.blocks.1.14.running_mean, backbone.middle_conv.3.bn2.bias, backbone.middle_conv.18.bn2.bias, backbone.middle_conv.18.bn1.running_var, bbox_head.tasks.0.conv_dir.bias, neck.blocks.1.4.weight, backbone.middle_conv.14.conv2.bias, neck.blocks.0.16.weight, neck.blocks.0.8.weight, backbone.middle_conv.13.bn2.weight, neck.blocks.0.14.running_var, neck.deblocks.0.0.weight, neck.deblocks.1.1.running_var, backbone.middle_conv.13.conv2.bias, neck.blocks.1.11.bias, backbone.middle_conv.13.conv2.weight, neck.blocks.0.17.running_var, backbone.middle_conv.19.bn1.running_mean, neck.blocks.0.14.bias, backbone.middle_conv.3.conv1.bias, backbone.middle_conv.18.bn1.bias, neck.blocks.0.8.running_var, backbone.middle_conv.13.bn1.running_mean, bbox_head.tasks.4.conv_cls.bias, neck.blocks.1.17.weight, neck.blocks.1.14.bias, backbone.middle_conv.14.bn2.bias, bbox_head.tasks.2.conv_box.weight, backbone.middle_conv.18.conv2.weight, backbone.middle_conv.9.bn1.running_var, backbone.middle_conv.3.bn2.weight, bbox_head.tasks.1.conv_box.weight, bbox_head.tasks.0.conv_cls.bias, backbone.middle_conv.19.conv1.weight, backbone.middle_conv.8.bn2.weight, neck.blocks.1.8.bias, bbox_head.tasks.0.conv_dir.weight, bbox_head.tasks.1.conv_cls.weight, bbox_head.tasks.1.conv_box.bias, bbox_head.tasks.4.conv_dir.bias, bbox_head.tasks.5.conv_cls.bias, neck.blocks.1.7.weight, backbone.middle_conv.19.conv2.weight, backbone.middle_conv.3.conv2.weight, neck.blocks.1.2.running_mean, backbone.middle_conv.14.conv2.weight, backbone.middle_conv.20.weight, neck.blocks.1.11.running_var, backbone.middle_conv.16.running_mean, backbone.middle_conv.16.bias, neck.blocks.0.1.weight, backbone.middle_conv.18.conv2.bias, backbone.middle_conv.6.bias, neck.blocks.1.11.running_mean, backbone.middle_conv.21.running_var, neck.blocks.0.2.running_var, backbone.middle_conv.4.bn1.bias, backbone.middle_conv.8.bn2.running_mean, backbone.middle_conv.14.bn1.running_mean, backbone.middle_conv.11.running_var, neck.blocks.0.4.weight, neck.blocks.0.14.weight, bbox_head.tasks.5.conv_box.weight, backbone.middle_conv.21.running_mean, neck.deblocks.1.1.running_mean, backbone.middle_conv.19.bn1.running_var, neck.blocks.0.14.running_mean, backbone.middle_conv.16.weight, backbone.middle_conv.9.bn2.running_mean, backbone.middle_conv.3.conv1.weight, backbone.middle_conv.4.bn1.running_var, backbone.middle_conv.3.bn1.running_var, neck.blocks.1.8.running_mean, bbox_head.tasks.1.conv_dir.bias, backbone.middle_conv.9.bn1.weight, backbone.middle_conv.18.bn1.running_mean, backbone.middle_conv.19.bn1.bias, backbone.middle_conv.14.bn1.running_var, backbone.middle_conv.19.conv2.bias, bbox_head.tasks.5.conv_cls.weight, backbone.middle_conv.3.conv2.bias, backbone.middle_conv.13.bn2.running_mean, backbone.middle_conv.15.weight, neck.blocks.1.13.weight, backbone.middle_conv.13.bn2.running_var, neck.blocks.0.10.weight, neck.blocks.0.8.running_mean, neck.blocks.0.7.weight

### LINKED ISSUE #117: No state_dict found in checkpoint file model_epoch_025_step_100100.pth
Hello,

1. Set up everything according to Installation and Getting Started for NuScenes trainval with only diffs:
-  OS: Ubuntu 18.04
-  Python: 3.6.9
-  PyTorch: 1.4
-  CUDA: 10.2
-  CUDNN: 7.6.5

2. Testing for NuScenes trainval with [provided checkpoint of cbgs](https://drive.google.com/file/d/11RmTy6fCgD8soXUcLr2zHaRe6aV4yCuI/view) and --nproc_per_node=1 (single gpu setup) :
```
./tools/scripts/test.sh examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py test/ /home/Downloads/model_epoch_025_step_100100.pth
```

3. Result:
```
2020-06-14 12:54:22,219 - INFO - Distributed testing: False
2020-06-14 12:54:22,219 - INFO - torch.backends.cudnn.benchmark: False
2020-06-14 12:54:22,298 - INFO - Finish RPN Initialization
2020-06-14 12:54:22,299 - INFO - num_classes: [1, 2, 2, 1, 2, 2], num_preds: [18, 36, 36, 18, 36, 36], num_dirs: [4, 8, 8, 4, 8, 8]
2020-06-14 12:54:22,302 - INFO - Finish MultiGroupHead Initialization
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/home/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /home/Downloads/model_epoch_025_step_100100.pth
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.6', '-u', './tools/dist_test.py', '--local_rank=0', 'examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py', '--work_dir=test/', '--checkpoint=/home/Downloads/model_epoch_025_step_100100.pth']' returned non-zero exit status 1.
```
Running the test without torch.distributed.launch gives the same result:
```
python3.6 tools/dist_test.py examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py --work_dir test/ --checkpoint /home/Downloads/model_epoch_025_step_100100.pth 
```
```
2020-06-14 12:58:52,101 - INFO - Distributed testing: False
2020-06-14 12:58:52,101 - INFO - torch.backends.cudnn.benchmark: False
2020-06-14 12:58:52,177 - INFO - Finish RPN Initialization
2020-06-14 12:58:52,178 - INFO - num_classes: [1, 2, 2, 1, 2, 2], num_preds: [18, 36, 36, 18, 36, 36], num_dirs: [4, 8, 8, 4, 8, 8]
2020-06-14 12:58:52,181 - INFO - Finish MultiGroupHead Initialization
Traceback (most recent call last):
  File "tools/dist_test.py", line 187, in <module>
    main()
  File "tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/home/pjoh/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /home/Downloads/model_epoch_025_step_100100.pth
```
Is the provided checkpoint faulty or not compatible with the current version of Det3D or am I doing something wrong?

### PR DESCRIPTION
**Pull request by tianweiy**
This pr is trying to fix #80 #117  #55  #47.  

I get an improved baselines based on a forked version of det3d. And now I move some of the changes from my repo to the original one. 

PointPillars:

Performance Improvement:

before this commit:

```
mAP: 0.2992                                                                                                                                                                                                                                   
mATE: 0.4408                                                                                                                                                                                                                                  
mASE: 0.2704                                                                                                                                                                                                                                  
mAOE: 0.9446                                                                                                                                                                                                                                  
mAVE: 0.5465                                                                                                                                                                                                                                  
mAAE: 0.2187                                                                                                                                                                                                                                  
NDS: 0.4075                                                                                                                                                                                                                                   
Eval time: 194.4s                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
Per-class results:                                                                                                                                                                                                                            
Object Class    AP      ATE     ASE     AOE     AVE     AAE                                                                                                                                                                                   
car     0.732   0.236   0.161   0.788   0.261   0.213                                                                                                                                                                                         
truck   0.336   0.470   0.210   0.702   0.298   0.249                                                                                                                                                                                         
bus     0.395   0.518   0.188   0.953   0.851   0.266                                                                                                                                                                                         
trailer 0.197   0.697   0.221   0.698   0.222   0.183                                                                                                                                                                                         
construction_vehicle    0.038   0.802   0.467   1.328   0.138   0.328                                                                                                                                                                         
pedestrian      0.543   0.328   0.282   1.450   1.013   0.213                                                                                                                                                                                 
motorcycle      0.109   0.292   0.237   1.477   0.983   0.274
bicycle 0.005   0.290   0.265   1.043   0.605   0.023
traffic_cone    0.265   0.273   0.365   nan     nan     nan
barrier 0.372   0.503   0.308   0.063   nan     nan
```

After this commit:

```
mAP: 0.4179
mATE: 0.3630
mASE: 0.2636
mAOE: 0.3770
mAVE: 0.2877
mAAE: 0.1983
NDS: 0.5600
Eval time: 81.2s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.801   0.215   0.159   0.191   0.251   0.205
truck   0.457   0.411   0.205   0.159   0.192   0.223
bus     0.558   0.444   0.192   0.126   0.532   0.308
trailer 0.278   0.617   0.202   0.478   0.157   0.172
construction_vehicle    0.103   0.757   0.434   1.159   0.114   0.346
pedestrian      0.717   0.163   0.277   0.432   0.244   0.088
motorcycle      0.321   0.230   0.246   0.354   0.599   0.215
bicycle 0.053   0.193   0.265   0.376   0.213   0.030
traffic_cone    0.437   0.188   0.358   nan     nan     nan
barrier 0.455   0.411   0.297   0.117   nan     nan
Evaluation nusc: Nusc v1.0-trainval Evaluation
car Nusc dist AP@0.5, 1.0, 2.0, 4.0
67.75, 81.12, 85.15, 86.46 mean AP: 0.8012047920593498
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0
23.71, 45.39, 54.92, 58.94 mean AP: 0.45739047966566226
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0
0.14, 5.21, 15.55, 20.37 mean AP: 0.10317209147626494
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0
26.23, 54.24, 69.76, 72.88 mean AP: 0.5577483330153783
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0
5.09, 21.19, 35.53, 49.41 mean AP: 0.2780347493252949
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0
25.15, 45.56, 53.82, 57.33 mean AP: 0.45465027132389
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
27.79, 32.90, 33.57, 33.96 mean AP: 0.3205635980429202
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
5.04, 5.26, 5.28, 5.45 mean AP: 0.05258777460814078
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0
68.81, 70.60, 72.70, 74.61 mean AP: 0.7168225670676128
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0
39.71, 41.46, 44.16, 49.28 mean AP: 0.4365392833724403
```

Summary of changes
- bug fixes in pillar encoder (this boosts to 39.1 map / 50.2 nds)
-  cos / sin encoding in contrast to directional encoder (both the original repo and my current one can't get directional classifier work on nuScenes) -> (35.4 map / 52.4 nds)
- flip along x/y axis during training + regression weight from 1 to 0.25 + filtering zero points box during training -> (41.8 map / 56 nds)

In my repo(which will come out next Monday), I can get (45.5 map / 58.4 nds). The remained changes to my knowledge are:
- I use a heavier head with 3 conv-bn-relu. (this should matter the most) 
- I use l1 loss in place of smooth-l1 loss (minor accuracy difference)
- I initialize the final classification conv layer's bias to -2.19 (following focal paper, not sure how much improvement)

Changing to a heavier head requires rewriting mg_head so I didn't do this here. 

CBGS

results will be added once finish.(tomorrow night) 

To use this newest commit, you need to regenerate all those info files to filter out zero point boxes during training. The other should be the same (no need to regenerate the gt database if you already have one).

I will provide pre-trained models once the pr is merged.

### CODE REVIEW

**Comment by poodarchu** [comment]
Can you provide corresponding checkpoints and training logs?

**Comment by tianweiy** [comment]
yes, the pointpillars model and checkpoint are available [here](https://drive.google.com/drive/folders/1U0bkEQAhcxhDUD42nTCGC0uU0qaTO_Uv?usp=sharing). I will add cbgs in 12 hours.

**Comment by tianweiy** [comment]
CBGS Updates:

before:

46.7 / 54.55 (copied from issue section)

```
mAP: 0.4669
mATE: 0.3391
mASE: 0.2574
mAOE: 0.7657
mAVE: 0.3162
mAAE: 0.2012
NDS: 0.5455
Eval time: 89.3s
2020-01-18 08:06:51,504 - INFO - 

2020-01-18 08:06:51,505 - INFO - Evaluation nusc: Nusc v1.0-trainval Evaluation
car Nusc dist AP@0.5, 1.0, 2.0, 4.0
68.54, 80.63, 84.63, 86.58 mean AP: 0.8009424366048317
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0
24.87, 44.61, 55.15, 58.78 mean AP: 0.45850578704319195
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0
0.17, 6.90, 16.21, 24.29 mean AP: 0.11890247733120854
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0
32.94, 56.79, 73.28, 76.13 mean AP: 0.5978476967252525
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0
4.21, 20.78, 37.94, 53.70 mean AP: 0.29155996509713616
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0
39.77, 55.13, 59.95, 62.47 mean AP: 0.5433129255795658
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
31.97, 39.27, 40.01, 40.37 mean AP: 0.3790460790422441
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
13.72, 14.36, 14.47, 14.65 mean AP: 0.1430066611617972
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0
72.81, 75.17, 76.99, 78.74 mean AP: 0.7592805073941438
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0
53.54, 55.51, 58.53, 63.15 mean AP: 0.5768369346063308
```

now:

```
mAP: 0.4990
mATE: 0.3353
mASE: 0.2563
mAOE: 0.3230
mAVE: 0.2505
mAAE: 0.1969
NDS: 0.6133
Eval time: 105.2s

Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.818	0.195	0.154	0.111	0.249	0.209
truck	0.492	0.392	0.197	0.097	0.199	0.229
bus	0.629	0.392	0.185	0.061	0.394	0.246
trailer	0.316	0.633	0.199	0.412	0.154	0.163
construction_vehicle	0.137	0.783	0.449	1.144	0.125	0.339
pedestrian	0.784	0.161	0.280	0.397	0.220	0.093
motorcycle	0.444	0.202	0.234	0.278	0.479	0.281
bicycle	0.208	0.166	0.263	0.319	0.185	0.015
traffic_cone	0.589	0.152	0.326	nan	nan	nan
barrier	0.574	0.277	0.276	0.089	nan	nan
Evaluation nusc: Nusc v1.0-trainval Evaluation
car Nusc dist AP@0.5, 1.0, 2.0, 4.0
70.72, 82.64, 86.00, 87.89 mean AP: 0.8181075796960271
truck Nusc dist AP@0.5, 1.0, 2.0, 4.0
27.03, 49.02, 58.66, 62.18 mean AP: 0.4922299142139578
construction_vehicle Nusc dist AP@0.5, 1.0, 2.0, 4.0
0.30, 6.93, 19.51, 27.89 mean AP: 0.13656648365947183
bus Nusc dist AP@0.5, 1.0, 2.0, 4.0
35.38, 60.28, 76.32, 79.46 mean AP: 0.6285951454369655
trailer Nusc dist AP@0.5, 1.0, 2.0, 4.0
4.82, 25.11, 43.58, 52.77 mean AP: 0.315690082891094
barrier Nusc dist AP@0.5, 1.0, 2.0, 4.0
43.22, 57.75, 62.99, 65.45 mean AP: 0.5735325513729088
motorcycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
39.19, 45.68, 46.28, 46.57 mean AP: 0.4442935931154901
bicycle Nusc dist AP@0.5, 1.0, 2.0, 4.0
20.15, 20.96, 21.02, 21.11 mean AP: 0.2081029978740392
pedestrian Nusc dist AP@0.5, 1.0, 2.0, 4.0
75.36, 77.71, 79.50, 81.18 mean AP: 0.7843566320006093
traffic_cone Nusc dist AP@0.5, 1.0, 2.0, 4.0
55.22, 57.02, 59.53, 63.66 mean AP: 0.5885651075883424
```

all files are available [here](https://drive.google.com/drive/folders/1rhamAqegE9iOp18tzQVam4rOMhHjjnRM?usp=sharing)

**Comment by poodarchu** [comment]
can you update the results in readme with links?

**Comment by tianweiy** [comment]
sure.

**Comment by tianweiy** [comment]
done

**Pull request merged**
